using System.Diagnostics;
using System.Text;
using ToastifyReloaded.Linux.Models;

namespace ToastifyReloaded.Linux.Services;

public sealed class XbindkeysService : IDisposable
{
    private readonly ProcessService _processService;
    private readonly LinuxSettingsService _settingsService;
    private Process? _process;

    public XbindkeysService(
        ProcessService processService,
        LinuxSettingsService settingsService)
    {
        _processService = processService;
        _settingsService = settingsService;
    }

    public string SessionType =>
        Environment.GetEnvironmentVariable("XDG_SESSION_TYPE")?.Trim().ToLowerInvariant()
        ?? "unknown";

    public bool IsWayland => SessionType == "wayland";

    public async Task<(bool Success, string Message)> ApplyAsync(LinuxSettings settings)
    {
        Stop();

        if (!settings.EnableX11GlobalHotkeys)
            return (true, "Hotkey globali disattivate.");

        if (IsWayland)
            return (
                false,
                "Sessione Wayland rilevata: il backend xbindkeys è riservato a X11/XWayland. Su Wayland viene usato XDG Global Shortcuts Portal.");

        if (!await _processService.ExistsAsync("xbindkeys"))
            return (
                false,
                "xbindkeys non trovato. Installa xbindkeys oppure usa il pacchetto .deb, che lo dichiara come dipendenza.");

        Directory.CreateDirectory(_settingsService.ConfigDirectory);
        var configPath = Path.Combine(
            _settingsService.ConfigDirectory,
            "xbindkeysrc");

        await File.WriteAllTextAsync(
            configPath,
            BuildConfig(settings),
            Encoding.UTF8);

        var startInfo = new ProcessStartInfo
        {
            FileName = "xbindkeys",
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true
        };
        startInfo.ArgumentList.Add("-n");
        startInfo.ArgumentList.Add("-f");
        startInfo.ArgumentList.Add(configPath);

        _process = Process.Start(startInfo);

        return _process is not null
            ? (true, "Hotkey globali X11 attive.")
            : (false, "Impossibile avviare xbindkeys.");
    }

    public void Stop()
    {
        try
        {
            if (_process is { HasExited: false })
                _process.Kill(entireProcessTree: true);
        }
        catch
        {
            // Best effort.
        }
        finally
        {
            _process?.Dispose();
            _process = null;
        }
    }

    private static string BuildConfig(LinuxSettings s)
    {
        var entries = new[]
        {
            (s.HotkeyPlayPause, "playerctl --player=spotify play-pause"),
            (s.HotkeyNext, "playerctl --player=spotify next"),
            (s.HotkeyPrevious, "playerctl --player=spotify previous"),
            (s.HotkeyVolumeUp, "playerctl --player=spotify volume 0.05+"),
            (s.HotkeyVolumeDown, "playerctl --player=spotify volume 0.05-"),
            (s.HotkeyMute, "playerctl --player=spotify volume 0"),
            (s.HotkeySeekForward, "playerctl --player=spotify position 10+"),
            (s.HotkeySeekBackward, "playerctl --player=spotify position 10-")
        };

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by Toastify Reloaded Linux");
        builder.AppendLine();

        foreach (var (shortcut, command) in entries)
        {
            if (string.IsNullOrWhiteSpace(shortcut))
                continue;

            builder.Append('"').Append(command).AppendLine("\"");
            builder.Append("  ").AppendLine(ToXbindkeys(shortcut));
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static string ToXbindkeys(string shortcut)
    {
        var parts = shortcut
            .Split('+', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

        if (parts.Length == 0)
            return shortcut;

        var modifiers = new List<string>();
        var key = parts[^1];

        foreach (var part in parts[..^1])
        {
            modifiers.Add(part.ToLowerInvariant() switch
            {
                "ctrl" or "control" => "Control",
                "alt" => "Alt",
                "shift" => "Shift",
                "super" or "win" or "meta" => "Mod4",
                _ => part
            });
        }

        var mappedKey = key.ToLowerInvariant() switch
        {
            "space" => "space",
            "right" => "Right",
            "left" => "Left",
            "up" => "Up",
            "down" => "Down",
            _ => key
        };

        return modifiers.Count == 0
            ? mappedKey
            : string.Join('+', modifiers) + " + " + mappedKey;
    }

    public void Dispose()
        => Stop();
}
